[CVSRP-4165 ]Employees First Furloughed Page not wired up but view renders
hmrc/coronavirus-jrs-calculator-frontend pull request #556
Opened 2021-02-04 12:44 UTC by william-hatzar

![image](https://user-images.githubusercontent.com/22661741/106894276-a4e64e00-66e6-11eb-995a-b311641bfa0b.png)

2021-02-04 14:35 UTC, peckoverHMRC requested changes

2021-02-04 14:35 UTC, peckoverHMRC commented on app/views/EmployeeFirstFurloughedView.scala.html
> +        @errorSummary(form.errors, Some("date-value.day"))
I think the error summary should go above the h1 unless the calculator works differently

2021-02-04 14:35 UTC, peckoverHMRC commented on conf/app.routes
> +GET        /employeeFirstFurloughed                              controllers.EmployeeFirstFurloughedController.onPageLoad()
urls are usually hyphenated. Might want to drop Georgie a message if there isn't one on the ticket/slides

2021-02-04 14:35 UTC, peckoverHMRC commented on conf/messages.en
> +employeeFirstFurloughed.checkYourAnswersLabel = EmployeeFirstFurloughed
this and a few of the error messages need updating

2021-02-04 14:35 UTC, peckoverHMRC commented on app/forms/EmployeeFirstFurloughedFormProvider.scala
> +  def apply(): Form[LocalDate] = Form("value" -> localDate(invalidKey = "employeeFirstFurloughed.error.invalid"))
Extra validation is needed either now or in another subtask

2021-02-24 09:12 UTC, MJCallahanPage commented
Will be merged as part of CVSRP-4170

2021-02-24 09:13 UTC, closed without merging