[CVSRP-4161] - Added new PreviousFurloughPeriods page
hmrc/coronavirus-jrs-calculator-frontend pull request #558
Opened 2021-02-05 12:07 UTC by BackRowOla

2021-02-05 12:22 UTC, BackRowOla commented
<img width="939" alt="Screenshot 2021-02-05 at 12 21 49" src="https://user-images.githubusercontent.com/56401572/107033157-cb6ebc80-67ac-11eb-9975-b1dfac3315e1.png">

2021-02-05 12:26 UTC, BackRowOla commented
Page not wired up but view renders

2021-02-16 11:16 UTC, peckoverHMRC requested changes

2021-02-16 11:16 UTC, peckoverHMRC commented on conf/messages.en
> +previousFurloughPeriods.checkYourAnswersLabel = previousFurloughPeriods
Is this used?

2021-02-16 11:16 UTC, peckoverHMRC commented on test/navigation/NavigatorSpecWithApplication.scala
> +        println("test for previous furluogh periods - currently not working")
:println:

2021-02-16 11:16 UTC, peckoverHMRC commented on test/navigation/NavigatorSpecWithApplication.scala
> +        println("test for RTI submission page")
:println:

2021-02-16 11:23 UTC, peckoverHMRC commented
all looks good to me. Just needs to be hooked up with CVSRP-4159 when its finished

2021-02-24 09:13 UTC, MJCallahanPage commented
To be merged as part of CVSRP-4170

2021-02-24 09:13 UTC, closed without merging