CVSRP-4575 Create new page for OnPayrollBefore30thOctober2020
hmrc/coronavirus-jrs-calculator-frontend pull request #572
Opened 2021-03-05 11:31 UTC by mywyau

2021-03-05 11:32 UTC, mywyau commented on conf/app.routes
> +
unsure what the url should be so asked for help

2021-03-05 12:04 UTC, mywyau commented
![Screenshot 2021-03-05 at 12 04 25](https://user-images.githubusercontent.com/47248104/110113399-f7c92900-7daa-11eb-8f40-8ed665a32624.png)

2021-03-08 10:11 UTC, JBlacklawsTen10 requested changes
Currently fails at RichJsValueSpec at "must remove a value given a keyPathNode and return the new object"

2021-03-08 13:21 UTC, mywyau commented
Cant seem to get that is it a test?

2021-03-08 15:47 UTC, JBlacklawsTen10 approved these changes
Page renders correctly and local tests pass

2021-03-08 16:02 UTC, merged