Cvsrp 4582b
hmrc/coronavirus-jrs-calculator-frontend pull request #577
Opened 2021-03-08 14:51 UTC by mywyau

2021-03-08 15:28 UTC, mywyau commented
branch made from CVSRP-4575

2021-03-09 11:11 UTC, mywyau commented on test/navigation/NavigatorSpecWithApplication.scala
> +          "go to correct next page" in {
old tests added back in

2021-03-09 11:13 UTC, LewisMitchell requested changes
Looks good, need to run the AT's and waiting for test result. Just a few minor test changes. 😄

2021-03-09 11:13 UTC, LewisMitchell commented on it/controllers/RegularLengthEmployedControllerISpec.scala
> +    "enters a No valid answer" when {
Could there also be a test for disabling the feature switch and it routing to the pay date page? Also a test for when the user enters 'Yes' and it also routes to the pay date page regardless of the feature switch state? As well as some kind of sad path (a bad request with an invalid form passed in)?

2021-03-09 11:13 UTC, LewisMitchell commented on test/navigation/NavigatorSpecWithApplication.scala
> +              EmployeeRTISubmissionPage,
**Could there be a test for when the user enters 'Yes' on this page and we ensure that the existing routing logic won't change?** The design says there will be a new page but we can just ensure that this routing still exists for now as we can change it later?

2021-03-09 12:29 UTC, mywyau commented on it/controllers/RegularLengthEmployedControllerISpec.scala
> +            .withPayDate(List("2020, 10, 31"))
note: I am assuming these are the mandatory answers needed just adjusted the claim start dates and stuff needed for this pages nav logic

2021-03-09 12:30 UTC, mywyau commented on it/controllers/RegularLengthEmployedControllerISpec.scala
> +            .withPayDate(List("2020, 10, 31"))
they have a method which builds monthly mandatory answers just based it off that
`  def mandatoryAnswersOnRegularMonthly =
    emptyUserAnswers
      .withClaimPeriodStart("2020, 3, 1")
      .withClaimPeriodEnd("2020, 3, 31")
      .withFurloughStartDate("2020, 3, 1")
      .withFurloughStatus()
      .withPaymentFrequency(Monthly)
      .withNiCategory()
      .withPensionStatus()
      .withPayMethod()
      .withLastPayDate("2020, 3, 31")
      .withPayDate(List("2020, 2, 29", "2020, 3, 31"))`

2021-03-09 15:55 UTC, merged