[CVSRP-4580] update and refactor Regular Pay Reference Pay to be one …
hmrc/coronavirus-jrs-calculator-frontend pull request #582
Opened 2021-03-10 15:25 UTC by peckoverHMRC

…dynamic page that handles all employee types

2021-03-10 15:25 UTC, peckoverHMRC commented
![Type1](https://user-images.githubusercontent.com/56835853/110653046-d6a27700-81b4-11eb-894d-0b6c69697dee.png)

Type 1

2021-03-10 15:25 UTC, peckoverHMRC commented
![Type2a](https://user-images.githubusercontent.com/56835853/110653103-e0c47580-81b4-11eb-914f-d1a7b3254c4c.png)

Type 2a

2021-03-10 15:26 UTC, peckoverHMRC commented
![Type2bWelsh](https://user-images.githubusercontent.com/56835853/110653160-ecb03780-81b4-11eb-8cd8-1c783edcdf7c.png)

Type 2b Welsh

2021-03-11 09:45 UTC, LewisMitchell requested changes
Acceptance tests fail for me 😢

2021-03-11 09:45 UTC, LewisMitchell commented on conf/messages.cy
> +regularPayAmount.p1 = This is the gross amount paid in the last pay period ending on or before {0}, before deductions.
I think there is a missing message `regularPayAmount.label`?

2021-03-11 09:45 UTC, LewisMitchell commented on it/controllers/RegularPayAmountControllerISpec.scala
> +      "redirect to LastPayDate page" in {
I think this needs to be changed to 'PartTimeQuestion page'

2021-03-11 18:03 UTC, peckoverHMRC commented
ATs pass against master

2021-03-12 15:26 UTC, LewisMitchell approved these changes
LGTM. Just running AT's.

2021-03-12 15:50 UTC, merged